apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dependencie-storage-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dependencie-storage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dependencie-storage
    spec:
      containers:
      - name: dependencie-storage
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-data
      volumes:
        - name: nfs-data
          persistentVolumeClaim:
            claimName: dependencie-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  name: dependencie-storage-endpoint
spec:
  type: ClusterIP
  ports:
    - name: rpcbind
      port: 111
      targetPort: 111
    - name: nfs
      port: 2049
      targetPort: 2049
    - name: mountd
      port: 20048
      targetPort: 20048
  selector:
    app: dependencie-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: build-dependencie-volume
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "127.0.0.1" #Warning this needs to be the IP not the Service Hostname! This is a bug tracked on github
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-dependencie-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
